### ISSUE TITLE
Host MDS has no NIDS 

### ISSUE THREAD

**Issue by 5soniyar** [whamcloud/integrated-manager-for-lustre#736] opened 2018-10-24 10:15 UTC
### Description 

We are using iml-4.0.8.0 to monitor existing lustre file-system. After adding server in monitored mode  while running detect file system it is throwing an error host mds has no NIDS. 

### Repro
The lustre file system is working fine and we able to do lctl ping to all mds, oss and client nodes. 

### Version
What version of IML?
iml- 4.0.8.0
What Operating System?
Centos7.5

![iml_error](https://user-images.githubusercontent.com/38415216/47423724-5cb7f180-d7a3-11e8-87db-742309ee7df4.PNG)

**Comment by jgrund** [comment] 2018-10-25 13:02
Duplicate of https://github.com/whamcloud/iml-common/issues/58

**Closed by jgrund** 2018-10-25 13:02 UTC
Labels: bug
