### ISSUE TITLE
how to build lustre with IB for deployment

### ISSUE THREAD

**Issue by kbuggenhout** [whamcloud/integrated-manager-for-lustre#651] opened 2018-06-12 15:11 UTC
### Description 

I am trying to make a bundle to deploy on MDS and OSS with IB cards, do we still need a specific build for MelanoxOFED, or is the standard build good enough? I have seen some issues on builds with the standard OFED with Lustre 2.4 where things went horribly wrong 

### Repro

no reproduction needed, lustre is built at installtime, but there is no support for building it with Mellanox OFED which may lead to instability.

### Version

What version of IML? 4.0.6
What Operating System? RH 7, CentOS 7
What Operating System version? 7.4/7.5

**Comment by kbuggenhout** [comment] 2018-06-15 14:43
one method was to install IML, then install the nodes, then run mlnx_add_kernel.sh on one of the installed storage servers, then create a new installer for MOFED, then run install on all of them, the proper modules are created, and runing ibstart enabled IB, then configure lnet to use IB as transport

there must be an easier way.

**Comment by kbuggenhout** [comment] 2018-06-15 19:50
but clearly that results in undefined symbols from the kernel when you try to load ko2ib for lnet, as this is compiled for opa. lol then we go back to the drawing board and build lustre rpms manually with zf and o2ib support

**Comment by johnsonw** [comment] 2018-06-20 12:55
Hi @kbuggenhout, sorry for not getting back to you sooner. Let me do some research on this. In the meantime, keep me updated on your other route.

**Comment by e73kiel** [comment] 2018-07-17 22:44
Hi @kbuggenhout  did you find a working way for your issue? I am facing the same problem.

**Comment by johnsonw** [comment] 2018-07-18 01:16
Hello @e73kiel and @kbuggenhout, i've been working on a solution for this. Please see the following document and keep in mind that it is still a work in progress: https://whamcloud.github.io/Support/docs/support/build-lustre-rpms-against-mellanox.html

Also, feel free to leave any feedback so I can continue to make this process better. Thanks.

**Comment by kbuggenhout** [comment] 2018-07-18 07:04
Thnx Will,

I see one big snag, building lustre with ib requires an option to the configure process of lustre. Configure —[options  to build lustre] —with-o2ib=/usr/src/ofa_kernel/default 
Without that lustre wont know about ib afaik.

Will try it out, but i am thinking of adding the option to the autoconf script, that detects if ib is installed and will build lustre accordingly. This will require the mlnx ofed to be installed during this process as well. Which is a bit dodgy.

Would it be an option to have a choice in iml, where iml will do the heavy lifting, select the latest correct mlnx ofed and build the kernel+lustre accordingly.

I have built quite a few lustre with mlnx ofed the old way. Then create the rpm artefacts.

With lustre 2.10.x it works, but the 2.11 branch fails as it tries to enable features that are removed in upstream kernels and in upstream mellanox ofed.

Will create a separate jira for that

K rgrds, Kris

**Comment by johnsonw** [comment] 2018-07-18 13:12
Thanks for the feedback @kbuggenhout. I am going to message a couple of people regarding the configuration option. One option is to allow configuration options to be passed to the provisioning script. I also plan on adding provisioners to add spl and zfs as well for those who run zfs filesystems. 

> Would it be an option to have a choice in iml, where iml will do the heavy lifting, select the latest 
> correct mlnx ofed and build the kernel+lustre accordingly.

I certainly agree that the current process of having the rpms built and then distributed is archaic and we need a better solution. Part of the problem is that we are not able to distribute mellanox, zfs, or spl binaries as they use gpl licensing. I like the idea of IML doing the heavy lifting as the purpose of IML is to make the whole process easier. One issue I see with this is that IML would need to be supplied with the mellanox driver; it's not possible (as far as I can tell) to fetch a specific driver without pysically going to their website, selecting the driver, and accepting the agreement before being able to download the file. That being said, if you were able to download the file and supply it to IML, IML might be able to take care of the rest. 

My current approach is to use the vagrant box such that anyone can generate the rpms and not rely on others to generate them. Let me discuss this with my team and see what direction they want to go. For now, you can always update the provisioning script in the vagrant file to add the "--with-o2ib" option. Please keep me updated and thanks again for the feedback.

Regards,

Will

**Comment by jgrund** [comment] 2019-07-26 22:58
This should be fixed now that https://github.com/whamcloud/integrated-manager-for-lustre/pull/955 has landed.

**Closed by jgrund** 2019-07-26 22:58 UTC
Labels: needs-docs
